import { lazy } from 'react'

// Maps a lesson slug to its lazily-loaded content component.
// Only lessons marked `ready: true` in curriculum.js need an entry here.
export const lessonComponents = {
  welcome: lazy(() => import('./Welcome.jsx')),
  'what-you-need': lazy(() => import('./WhatYouNeed.jsx')),
  variables: lazy(() => import('./Variables.jsx')),
  functions: lazy(() => import('./Functions.jsx')),
  'arrays-objects': lazy(() => import('./ArraysObjects.jsx')),
  destructuring: lazy(() => import('./Destructuring.jsx')),
  'spread-rest': lazy(() => import('./SpreadRest.jsx')),
  'promises-async-await': lazy(() => import('./PromisesAsyncAwait.jsx')),
  'template-literals': lazy(() => import('./TemplateLiterals.jsx')),
  modules: lazy(() => import('./Modules.jsx')),
  'what-is-react': lazy(() => import('./WhatIsReact.jsx')),
  'first-project': lazy(() => import('./FirstProject.jsx')),
  'rendering-to-the-dom': lazy(() => import('./RenderingToTheDom.jsx')),
  'what-is-jsx': lazy(() => import('./WhatIsJsx.jsx')),
  'jsx-expressions': lazy(() => import('./JsxExpressions.jsx')),
  'jsx-rules': lazy(() => import('./JsxRules.jsx')),
  'conditional-rendering': lazy(() => import('./ConditionalRendering.jsx')),
  'rendering-lists': lazy(() => import('./RenderingLists.jsx')),
  'first-component': lazy(() => import('./FirstComponent.jsx')),
  'importing-exporting': lazy(() => import('./ImportingExporting.jsx')),
  props: lazy(() => import('./Props.jsx')),
  composing: lazy(() => import('./Composing.jsx')),
  'ui-as-a-tree': lazy(() => import('./UiAsATree.jsx')),
  'pure-components': lazy(() => import('./PureComponents.jsx')),
  'click-events': lazy(() => import('./ClickEvents.jsx')),
  'form-events': lazy(() => import('./FormEvents.jsx')),
  'use-state': lazy(() => import('./UseState.jsx')),
  'render-and-commit': lazy(() => import('./RenderAndCommit.jsx')),
  'state-snapshot': lazy(() => import('./StateSnapshot.jsx')),
  'updating-state': lazy(() => import('./UpdatingState.jsx')),
  'updating-objects': lazy(() => import('./UpdatingObjects.jsx')),
  'updating-arrays-in-state': lazy(() => import('./UpdatingArraysInState.jsx')),
  'lifting-state-up': lazy(() => import('./LiftingStateUp.jsx')),
  'choosing-state-structure': lazy(() => import('./ChoosingStateStructure.jsx')),
  'preserving-resetting-state': lazy(() => import('./PreservingResettingState.jsx')),
  'use-effect': lazy(() => import('./UseEffect.jsx')),
  'you-might-not-need-an-effect': lazy(() => import('./YouMightNotNeedAnEffect.jsx')),
  'effect-timing': lazy(() => import('./EffectTiming.jsx')),
  'effect-dependencies': lazy(() => import('./EffectDependencies.jsx')),
  'use-ref': lazy(() => import('./UseRef.jsx')),
  'use-reducer': lazy(() => import('./UseReducer.jsx')),
  'use-context': lazy(() => import('./UseContext.jsx')),
  'custom-hooks': lazy(() => import('./CustomHooks.jsx')),
  'basic-routing': lazy(() => import('./BasicRouting.jsx')),
  navigation: lazy(() => import('./Navigation.jsx')),
  'route-parameters': lazy(() => import('./RouteParameters.jsx')),
  'mini-project': lazy(() => import('./MiniProject.jsx')),
  'intro-to-typescript': lazy(() => import('./IntroToTypescript.jsx')),
}
